"""Oracle-guided (DAgger) training data, generated by playing the real game.

Cloning an exact planner's optimal path teaches a policy nothing about the
states it reaches once it slips off that path, and a policy that cannot recover
loses the level on its first mistake. So states off the optimal path have to be
in the data, labelled with the oracle's optimal action *at that state*.

How they get there matters. Uniform epsilon-greedy noise is the obvious way and
it is mostly the wrong one: LS20's step budget is tight, so random detours make
levels permanently unwinnable. Measured over 40 generated levels, completed
episodes fell from 32/40 at epsilon .05 to 23/40 at .10, 15/40 at .20 and 10/40
at .25, where the oracle declared the state hopeless 30 times. Hence epsilon 0
by default on a bank, and the mechanisms that do the real work. Prefix-replay
deviation: replay k optimal actions on a *fresh* level, stray for a run of
deliberately wrong ones, then follow the oracle again, labelling every state
from the first mistake onwards. And a pad-targeted branch: walk up to a goal
pad still carrying the wrong triple, which is the state a trained policy
actually dies in and the one place the oracle never goes by itself.

Planning, not playing, is what costs: an oracle build runs from hundredths of a
second at difficulty 1 to seconds at 4 and 5. A verified level spec already
carries an optimal, replay-verified solution, so the on-path trajectory is free
-- replay it and the label and the distance to completion are both known. The
planner is built lazily and only the deviation branches pay for it.

Levels come either from a bank of pre-verified specs (the split of record, whose
seed ranges keep train, validation and test apart) or from seeds generated on
demand. Either way one level plays per episode and per environment, and every
sample carries its level seed, so the trainer can split by seed with no leakage.

Most states have more than one right answer. Measured over 981 on-path states,
70.0% had exactly one optimal action, 22.3% two, 5.6% three and 2.0% four, a
mean of 1.397 -- so a policy that always played optimally would match a single
arbitrary label only ~84% of the time, and cross-entropy against that label
docks it for playing well. Every sample therefore carries `optimal`, a bitmask
of every action that is optimal at that state, with the recorded label's own bit
always set. That is the v2 format; v1 shards still load, with the mask
synthesised as the label's bit alone.

`to_go`, the oracle's optimal distance to completion at each state, is written
to every shard. It is kept for analysis and curriculum work even when no model
head consumes it, so it should not be dropped from the format.

The game, the generator, the bank and the planner are imported lazily. Importing
this module must work in a checkout where they do not exist yet -- reading,
merging and inspecting shards needs none of them.
"""

import argparse
from collections import deque
from datetime import datetime, timezone
import importlib
import json
import multiprocessing
from pathlib import Path
import random
import sys

import numpy as np

from ..ls20 import names

DATA_FORMAT = "pebby.ls20-oracle.v2"
LEGACY_FORMATS = ("pebby.ls20-oracle.v1",)  # v1 predates `optimal`; still readable
ACTION_COUNT = len(names.ACTION_IDS)
ARRAYS = ("frames", "actions", "to_go", "seeds", "optimal")
# A level's step budget is far below this; the cap only bounds memory if a
# planner and the game ever disagree and an episode refuses to end.
MAX_ACTIONS = 400
EPSILON = .05           # for seed runs; a bank defaults to 0, see the docstring
DEVIATIONS = 4          # off-path branches per level
DEVIATION_FOLLOW = 6    # oracle-guided recovery steps recorded per branch
DEVIATION_STEPS = 6     # a branch strays 1..this many actions before recovering
PAD_BRANCHES = 1        # branches that walk up to a goal pad carrying the wrong triple
PAD_STEPS = 24          # cap on the route to a pad; the lattice is 12x12


# -- lazy access to the game ---------------------------------------------------

def _module(name):
    """Import `pebby.ls20.<name>` on first use, never at import time."""
    full = f"pebby.ls20.{name}"
    try:
        return importlib.import_module(full)
    except ImportError as error:
        # Only claim the module is missing when it is; an ImportError raised
        # from inside it is a different bug and must not be relabelled.
        if getattr(error, "name", full) != full:
            raise
        raise RuntimeError(f"{full} is missing: LS20 level generation and planning are not "
                           "implemented yet, so no data can be generated.") from error


def generator_version():
    """Resolved while generating, because the generator may not exist at import."""
    try:
        return getattr(_module("generate"), "GENERATOR_VERSION", "unknown")
    except RuntimeError:
        return "unknown"


def __getattr__(name):
    # `data.GENERATOR_VERSION` reads like a constant but cannot be one: binding
    # it at import would drag the generator in exactly where it may be absent.
    if name == "GENERATOR_VERSION":
        return generator_version()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def load_bank(path, limit=None):
    """Compatible geometry; episode collection checks or rebuilds context proof."""
    specs = _module("bank").load(path)
    return specs[:limit] if limit else specs


def _split_of(specs):
    """Which named split these seeds belong to, or None if they are mixed.

    The bank keeps splits apart by seed range rather than by a field on the
    spec, so the range is what can be read back out of one.
    """
    try:
        bounds = sorted(getattr(_module("bank"), "SPLIT_SEEDS", {}).items(), key=lambda item: -item[1])
    except RuntimeError:
        return None
    found = {next((name for name, base in bounds if spec.get("seed", 0) >= base), None)
             for spec in specs}
    return found.pop() if len(found) == 1 else None


# -- labelling one state -------------------------------------------------------

def _oracle_action(value):
    """Reject a 0-based oracle loudly; silently it would mislabel every state."""
    if value is not None and value not in names.ACTION_IDS:
        raise ValueError(f"oracle returned {value!r}; it must return an ARC action id from "
                         f"{names.ACTION_IDS} (1=up, 2=down, 3=left, 4=right) or None")
    return value


def _available(observation):
    """The action ids the game says are legal, whichever enum it reports them as."""
    return tuple(getattr(action, "value", action) for action in (observation.available_actions or ()))


def _remaining(oracle, env):
    """Optimal actions left from where the game stands now, or None if unknown.

    The oracle built at the level's start already holds the distance to every
    reachable state, so this is a lookup. Never rebuild one mid-level to answer
    it: `layout.extract` reads the step budget from the HUD's *maximum* while
    the live state carries what is left of it, so a fresh oracle does not
    contain the state you are standing in and calls it hopeless. An oracle that
    offers no lookup gets an honest -1 rather than a fabricated distance.
    """
    if hasattr(oracle, "distance_for") and hasattr(oracle, "state_of"):
        return oracle.distance_for(oracle.state_of(env))
    return None


def _optimal_mask(oracle, env, expert):
    """Bitmask of every action that is optimal here, and whether it is exact.

    A tie is the normal case, not an edge case, so labelling one arbitrary
    winner teaches the policy to hedge -- and a hedge loses under argmax. The
    planner already knows the whole set: an action is optimal exactly when the
    state it leads to is one step closer to done. `plan.advance` walks that
    transition on the planner's own state, so the four probes cost no game steps
    at all. Without a layout or a known distance the honest answer is the
    label's bit alone, reported as inexact and counted in `meta`.
    """
    bit = 1 << names.ACTION_IDS.index(expert)
    if getattr(oracle, "truncated", False):
        # A reachable winning route is not an exhaustive optimal-action set.
        return bit, False
    layout = getattr(oracle, "layout", None)
    advance = getattr(_module("plan"), "advance", None)
    if layout is None or advance is None or not hasattr(oracle, "state_of"):
        return bit, False
    state = oracle.state_of(env)
    distance = oracle.distance_for(state)
    if distance is None:
        return bit, False
    mask = 0
    for index in range(ACTION_COUNT):
        following = advance(layout, state, index, oracle.refills)
        if following is not None and oracle.distance_for(following) == distance - 1:
            mask |= 1 << index
    if not mask & bit:
        raise ValueError(f"oracle chose action {expert} but its own optimal set here is "
                         f"{mask:04b}; the planner disagrees with itself")
    return mask, True


def _record(rows, env, oracle, expert, remaining, available):
    """Label the frame as it is *before* the action: the label for the frame
    observed at time t is the action taken after observing it, which is what the
    policy is asked to predict. Only this pre-action render is ever recorded --
    one `perform` can emit six frames and the intermediate ones can be a solid
    death-flash fill with no HUD, which is not a state any policy should see."""
    if expert not in available:
        raise ValueError(f"oracle chose action {expert} where the game offers {available}; "
                         "planner and game disagree about this state")
    mask, exact = (_optimal_mask(oracle, env, expert) if oracle is not None
                   else (1 << names.ACTION_IDS.index(expert), False))
    rows["frames"].append(np.asarray(env.render(), dtype=np.uint8))
    rows["actions"].append(names.ACTION_IDS.index(expert))
    rows["to_go"].append(-1 if remaining is None else remaining)
    rows["optimal"].append(mask)
    rows["exact"].append(exact)


def _replay(env, solution, rows, oracle=None):
    """Record a verified solution without planning the path itself.

    `spec["solution"]` is optimal and was replayed in the real game before the
    level was accepted, so the label at step t is its own action and `to_go` is
    exactly the number of actions left in it -- no planner needed for either.
    `oracle` is only consulted for the optimal-action mask, and only when the
    branches have already paid to build one. Returns (steps, completed).
    """
    available, completed, steps = names.ACTION_IDS, False, 0
    for index, action in enumerate(solution):
        _record(rows, env, oracle, _oracle_action(action), len(solution) - index, available)
        observation = env.perform(action)
        steps += 1
        available = _available(observation)
        if observation.finished or env.levels_completed:
            completed = bool(observation.won or env.levels_completed)
            break
    return steps, completed


def _walk(env, oracle, rng, epsilon, limit, rows, available=names.ACTION_IDS):
    """Play up to `limit` actions, labelling every state with the oracle's move.

    `rng` only ever needs `random()` and `choice()`, so a `random.Random` and a
    `numpy.random.Generator` both work. Returns (steps, completed, hopeless).
    """
    solved = env.levels_completed
    remaining, steps, completed, hopeless = None, 0, False, False
    while steps < limit:
        expert = _oracle_action(oracle.action_at(env))
        if expert is None:
            hopeless = True  # Hopeless states stay hopeless; nothing beyond one is labellable.
            break
        if remaining is None:
            remaining = _remaining(oracle, env)
        _record(rows, env, oracle, expert, remaining, available)
        action = int(rng.choice(names.ACTION_IDS)) if rng.random() < epsilon else expert
        observation = env.perform(action)
        steps += 1
        available = _available(observation)
        # Following the oracle shortens the optimal remainder by exactly one; a
        # detour can lengthen it, so only a detour needs a fresh lookup, which
        # has to re-read every sprite to find the refills still standing.
        remaining = remaining - 1 if remaining and action == expert else None
        if observation.finished or env.levels_completed > solved:
            completed = bool(observation.won or env.levels_completed > solved)
            break
    return steps, completed, hopeless


# -- straying off the optimal path ---------------------------------------------

def _manhattan(cell, other):
    return abs(cell[0] - other[0]) + abs(cell[1] - other[1])


def _step_cell(cell, action):
    dx, dy = names.ACTION_DELTAS[names.ACTION_IDS.index(action)]
    return (cell[0] + dx, cell[1] + dy)


def _route_to_pad(layout, rng, start, pad):
    """Actions that walk from `start` to a cell next to `pad`, or [] if none.

    A breadth-first route rather than the obvious greedy walk: greedy stalls in
    a corner, and a stalled move still costs step budget, so the branch would
    die on the way to the state it exists to record. Ties are broken randomly so
    several pad branches on one level do not retrace one route. Goal cells are
    not walked through -- an unmatched pad is solid and a matched one would
    clear the goal, which is the opposite of the point.
    """
    goals = getattr(layout, "goal_at", {})
    previous, queue = {tuple(start): None}, deque([tuple(start)])
    while queue:
        cell = queue.popleft()
        if _manhattan(cell, pad) == 1:
            route = []
            while previous[cell] is not None:
                cell, action = previous[cell]
                route.append(action)
            return route[::-1]
        for action in sorted(names.ACTION_IDS, key=lambda _: rng.random()):
            target = _step_cell(cell, action)
            if target in previous or target in goals or not layout.free(target):
                continue
            previous[target] = (cell, action)
            queue.append(target)
    return []


def _stray(env, oracle, rng, limit, rows, available, choose):
    """Take up to `limit` actions of someone else's choosing, labelling every
    state passed through with the oracle's optimal action at that state.

    Those labels are the lesson: the policy has to be told what the right move
    is from where a mistake actually left it, not only from the optimal path.
    The first state is not recorded, because a branch starts on the path the
    on-path pass already covered and a duplicate would only re-weight it.
    `choose` returns None to stop early. Returns (steps, available, hopeless, finished).
    """
    steps, hopeless, finished = 0, False, False
    while steps < limit:
        expert = _oracle_action(oracle.action_at(env))
        if expert is None:
            hopeless = True
            break
        if steps:
            _record(rows, env, oracle, expert, _remaining(oracle, env), available)
        action = choose(env, expert, available)
        if action is None:
            break
        observation = env.perform(action)
        steps += 1
        available = _available(observation)
        if observation.finished or env.levels_completed:
            finished = True
            break
    return steps, available, hopeless, finished


# -- one episode ---------------------------------------------------------------

def deviation_samples(new_env, oracle, solution, rng, rows, branches=DEVIATIONS,
                      follow=DEVIATION_FOLLOW, steps=DEVIATION_STEPS):
    """Off-path states, a run of deliberate mistakes at a time.

    Each branch replays a prefix of the optimal solution on a *fresh* level,
    strays for 1..`steps` actions the oracle would not take, and then follows
    the oracle again for `follow` steps. Every state from the first mistake
    onwards is labelled, so the data covers being several moves adrift, not just
    one. A single-action detour barely leaves the optimal corridor, which is how
    whole regions of the level -- the goal pad approached with the wrong triple,
    above all -- stayed out of the training set.

    Each branch spends its mistakes on an intact level: accumulating them inside
    one episode runs the step budget out and the rest of the level teaches
    nothing. Returns (branches taken, branches the mistakes made hopeless).
    """
    taken, hopeless = 0, 0
    for _ in range(branches):
        if not solution:
            break
        env = new_env()
        available = names.ACTION_IDS
        for action in solution[:int(rng.random() * len(solution))]:
            available = _available(env.perform(action))

        def choose(env, expert, available):
            choices = [action for action in available if action != expert]
            return int(rng.choice(choices)) if choices else None

        wrong = 1 + int(rng.random() * max(1, steps))
        moved, available, dead, finished = _stray(env, oracle, rng, wrong, rows, available, choose)
        if not moved:
            continue
        taken += 1
        hopeless += dead
        if dead or finished:
            continue  # The mistakes ended the level; there is no recovery to show.
        hopeless += _walk(env, oracle, rng, 0., follow, rows, available)[2]
    return taken, hopeless


def pad_samples(new_env, oracle, rng, rows, branches=PAD_BRANCHES, follow=DEVIATION_FOLLOW,
                limit=PAD_STEPS):
    """Branches that walk up to a goal pad while carrying the wrong triple.

    The oracle never produces this state -- `plan.advance` prunes a rejected pad
    bump because it changes nothing -- yet it is where a trained policy dies.
    A pad refuses an unmatched triple *before* the budget is charged, so the
    refused bump leaves the frame byte-identical, and a deterministic argmax fed
    an identical frame repeats it forever. Measured on a trained policy, 74% of
    3,684 actions left the frame unchanged and every one inspected was a free
    pad bump. Nothing else in this file produces that state, so nothing else can
    teach the only way out of it: cycle first, approach second.

    Returns (branches taken, branches that reached a pad still mismatched,
    branches the walk made hopeless).
    """
    layout = getattr(oracle, "layout", None)
    goals = getattr(layout, "goals", None) or ()
    taken, adjacent, hopeless = 0, 0, 0
    for _ in range(branches):
        if not goals:
            break
        env = new_env()
        cell, wanted = goals[int(rng.random() * len(goals))]
        if tuple(env.triple()) == tuple(wanted):
            continue  # Already matching: this branch would teach the easy case.
        route = _route_to_pad(layout, rng, env.player_cell(), cell)[:limit]
        if not route:
            continue
        taken += 1
        walk = iter(route)
        moved, available, dead, finished = _stray(env, oracle, rng, len(route), rows,
                                                  names.ACTION_IDS, lambda *_: next(walk, None))
        hopeless += dead
        if dead or finished:
            continue
        if _manhattan(env.player_cell(), cell) == 1 and tuple(env.triple()) != tuple(wanted):
            adjacent += 1
        # Label from here on: this first state is the one the policy gets stuck in.
        hopeless += _walk(env, oracle, rng, 0., follow, rows, available)[2]
    return taken, adjacent, hopeless


def episode_from_spec(spec, epsilon, rng, max_actions=None, deviations=DEVIATIONS,
                      follow=DEVIATION_FOLLOW, steps=DEVIATION_STEPS, pads=PAD_BRANCHES):
    """One verified level: its on-path trajectory, deviation branches and pad branches."""
    env_module, generate, plan = _module("env"), _module("generate"), _module("plan")
    context_index = spec["seed"] % 7
    if context_index == 0 and spec.get("launchers"):
        raise ValueError("context-zero launcher hints are outside the oracle state")

    def new_env():
        """Sprites carry level state, so every branch needs its own game."""
        return _one_level_env(env_module, generate.build_levels([spec]), context_index)

    limit = MAX_ACTIONS if max_actions is None else max_actions
    solution = spec.get("solution") or []
    context_proved = (spec.get("context_engine_verified") is True
                      and spec.get("search_truncated") is False
                      and spec.get("verification_level_index") == context_index
                      and spec.get("context_solution") == solution
                      and spec.get("context_optimal_actions") == len(solution)
                      and spec.get("optimal_actions") == len(solution))
    rows = {"frames": [], "actions": [], "to_go": [], "optimal": [], "exact": []}
    hopeless = False
    env = new_env()
    # The planner is what a level costs, so build it only when something needs
    # it: noise, a spec with no solution, or any branch. An oracle is valid only
    # at a level's start, which is where this one is built, and its distance
    # table then covers the rollout, every branch and every optimal-set mask.
    branching = (deviations or pads) and solution
    oracle = plan.oracle_for(env) if (epsilon or not solution or branching or not context_proved) else None
    if oracle is not None and (oracle.truncated or not oracle.solvable):
        raise ValueError("legacy collection requires a complete solvable contextual oracle")
    if not context_proved:
        solution = oracle.solution(seed=spec["seed"])
        proof_env = new_env()
        result = None
        for action in solution or ():
            result = proof_env.perform(action)
        if result is None or not result.won or proof_env.lives() != 3:
            raise ValueError("legacy contextual solution failed engine verification")
    if epsilon or not solution:
        walked, completed, hopeless = _walk(env, oracle, rng, epsilon, limit, rows)
    else:
        walked, completed = _replay(env, solution[:limit], rows, oracle)
    taken, dead, pad_taken, pad_adjacent = 0, 0, 0, 0
    if branching:
        if deviations:
            taken, dead = deviation_samples(new_env, oracle, solution, rng, rows, deviations,
                                            follow, steps)
        if pads:
            pad_taken, pad_adjacent, pad_dead = pad_samples(new_env, oracle, rng, rows, pads, follow)
            dead += pad_dead
    sizes = [int(mask).bit_count() for mask in rows["optimal"]]
    return {"frames": np.stack(rows["frames"]) if rows["frames"] else _blank()["frames"],
            "actions": np.array(rows["actions"], dtype=np.uint8),
            "to_go": np.array(rows["to_go"], dtype=np.int16),
            "optimal": np.array(rows["optimal"], dtype=np.uint8),
            "seed": int(spec.get("seed", -1)), "difficulty": spec.get("difficulty"),
            "source_generator_version": spec.get("generator_version"),
            "context_index": context_index,
            "steps": walked, "completed": completed,
            "oracle_length": len(solution) if solution else -1,
            "hopeless": hopeless, "branches": taken, "hopeless_branches": dead,
            "pad_branches": pad_taken, "pad_adjacent": pad_adjacent,
            "multi_optimal": sum(1 for size in sizes if size > 1), "optimal_total": sum(sizes),
            "mask_fallbacks": sum(1 for exact in rows["exact"] if not exact)}


def episode(seed, difficulty, epsilon, rng, max_actions=None, deviations=DEVIATIONS,
            follow=DEVIATION_FOLLOW, steps=DEVIATION_STEPS, pads=PAD_BRANCHES):
    """One level generated on demand for `seed`, then played like a banked one."""
    spec = _module("generate").generate_level(seed, difficulty)
    return episode_from_spec(spec, epsilon, rng, max_actions, deviations, follow, steps, pads)


# -- shards --------------------------------------------------------------------

def _one_level_env(env_module, levels, context_index=0):
    """A data env always holds exactly the one generated level it was given.

    `Ls20Env(None)` quietly plays the seven shipped levels, and those are
    evaluation-only: a shard containing them would make every evaluation number
    a lie. One level per env is also what makes a sample attributable to a
    single seed, so the count is worth asserting rather than assuming.
    """
    if levels is None or len(levels) != 1:
        raise ValueError("a data env must hold exactly one generated level; "
                         "the shipped levels are evaluation-only")
    env = env_module.Ls20Scenario(levels[0], context_index)
    return env


def _blank():
    """Empty arrays with the exact dtypes a shard promises, for the no-sample cases."""
    return {"frames": np.zeros((0, names.FRAME_SIZE, names.FRAME_SIZE), dtype=np.uint8),
            "actions": np.zeros(0, dtype=np.uint8), "to_go": np.zeros(0, dtype=np.int16),
            "seeds": np.zeros(0, dtype=np.int32), "optimal": np.zeros(0, dtype=np.uint8)}


def _episode_rng(rng_seed, seed):
    """Seed from the (run, level) pair rather than from one shared stream, so a
    level plays out the same way however many workers split the run. String
    seeding goes through SHA-512, which is stable across processes."""
    return random.Random(f"{DATA_FORMAT}:{rng_seed}:{seed}")


def _run_specs(task):
    """Runs inside a worker: the env is built here, because it cannot be pickled."""
    specs, epsilon, rng_seed, max_actions, branching = task
    return [episode_from_spec(spec, epsilon, _episode_rng(rng_seed, spec.get("seed", -1)),
                              max_actions, **branching) for spec in specs]


def _run_chunk(task):
    """Same, for seeds: generating the level is the worker's job, not the parent's."""
    seeds, difficulty, epsilon, rng_seed, max_actions, branching = task
    return [episode(seed, difficulty, epsilon, _episode_rng(rng_seed, seed), max_actions,
                    **branching) for seed in seeds]


def _chunks(items, workers):
    """Several levels per task -- one task per level spends more time starting
    processes than playing -- but enough tasks to even out slow levels."""
    size = max(1, (len(items) + workers * 4 - 1) // (workers * 4))
    return [items[index:index + size] for index in range(0, len(items), size)]


def _drive(worker, tasks, total, workers, progress):
    episodes = []
    if workers > 1 and len(tasks) > 1:
        # Spawn, not fork: the game is loaded from a file by path and generated
        # levels are installed on that module, which a forked copy would inherit.
        with multiprocessing.get_context("spawn").Pool(workers) as pool:
            for done in pool.imap(worker, tasks):  # imap keeps the level order
                episodes.extend(done)
                _report(progress, episodes, total)
    else:
        for task in tasks:
            episodes.extend(worker(task))
            _report(progress, episodes, total)
    return episodes


def _report(progress, episodes, total):
    if progress:
        print(f"{len(episodes)}/{total} levels | "
              f"{sum(len(item['frames']) for item in episodes)} samples | "
              f"{sum(item['completed'] for item in episodes)} completed", file=sys.stderr, flush=True)


def _difficulty(counts):
    """One number when a shard is uniform, None when a bank mixed difficulties."""
    present = sorted(int(key) for key, count in counts.items() if count and key != "None")
    return present[0] if len(present) == 1 else None


def _collect(episodes, epsilon, rng_seed, max_actions, branching, bank=None, split=None):
    # Every sample carries its level seed, which is how the trainer splits train
    # from validation without one level straddling both sides.
    columns = {key: [item[key] for item in episodes] for key in ARRAYS if key != "seeds"}
    columns["seeds"] = [np.full(len(item["frames"]), item["seed"], dtype=np.int32) for item in episodes]
    shard = {key: np.concatenate(value) if value else _blank()[key] for key, value in columns.items()}
    counts = {}
    for item in episodes:
        counts[str(item["difficulty"])] = counts.get(str(item["difficulty"]), 0) + 1
    shard["meta"] = {
        "format": DATA_FORMAT, "generator_version": generator_version(),
        "source_generator_versions": sorted({item.get("source_generator_version")
                                              for item in episodes}, key=str),
        "context_indices": [item.get("context_index") for item in episodes],
        "seeds": [item["seed"] for item in episodes], "difficulty": _difficulty(counts),
        "difficulty_counts": counts, "bank": None if bank is None else str(bank), "split": split,
        "epsilon": epsilon, "rng_seed": rng_seed,
        "samples": int(len(shard["frames"])), "episodes": len(episodes),
        "completed_episodes": sum(1 for item in episodes if item["completed"]),
        "hopeless_rollouts": sum(1 for item in episodes if item["hopeless"]),
        "deviations": branching["deviations"], "deviation_follow": branching["follow"],
        "deviation_steps": branching["steps"], "pad_branches_requested": branching["pads"],
        "deviation_branches": sum(item["branches"] for item in episodes),
        "hopeless_branches": sum(item["hopeless_branches"] for item in episodes),
        "pad_branches": sum(item["pad_branches"] for item in episodes),
        "pad_adjacent_branches": sum(item["pad_adjacent"] for item in episodes),
        "multi_optimal_samples": sum(item["multi_optimal"] for item in episodes),
        "optimal_set_mean": round(sum(item["optimal_total"] for item in episodes)
                                  / max(1, sum(len(item["frames"]) for item in episodes)), 4),
        "mask_fallbacks": sum(item["mask_fallbacks"] for item in episodes),
        "action_count": ACTION_COUNT, "frame_size": names.FRAME_SIZE,
        "max_actions": MAX_ACTIONS if max_actions is None else max_actions,
        "steps": sum(item["steps"] for item in episodes),
        "oracle_lengths": [item["oracle_length"] for item in episodes],
        "created": datetime.now(timezone.utc).isoformat(timespec="seconds")}
    return shard


def _branching(deviations, follow, steps, pads):
    """The four branch knobs travel together, to workers and into `meta`."""
    return {"deviations": deviations, "follow": follow, "steps": steps, "pads": pads}


def generate_shard_from_specs(specs, epsilon=0., seed=0, max_actions=None, workers=1, progress=False,
                              deviations=DEVIATIONS, follow=DEVIATION_FOLLOW, steps=DEVIATION_STEPS,
                              pads=PAD_BRANCHES, bank=None):
    """Play a bank of verified level specs and concatenate the labelled states."""
    specs = list(specs)
    branching = _branching(deviations, follow, steps, pads)
    tasks = [(chunk, epsilon, seed, max_actions, branching) for chunk in _chunks(specs, workers)]
    episodes = _drive(_run_specs, tasks, len(specs), workers, progress)
    return _collect(episodes, epsilon, seed, max_actions, branching, bank, _split_of(specs))


def generate_shard(seeds, difficulty, epsilon, seed=0, max_actions=None, workers=1, progress=False,
                   deviations=DEVIATIONS, follow=DEVIATION_FOLLOW, steps=DEVIATION_STEPS,
                   pads=PAD_BRANCHES):
    """Generate a level per seed and play it. `generate_shard_from_specs` is the
    cheaper path when a bank already exists; this one plans every level afresh.

    `workers > 1` starts processes, so a caller that is not the CLI needs the
    usual `if __name__ == "__main__":` guard around it.
    """
    seeds = [int(value) for value in seeds]
    branching = _branching(deviations, follow, steps, pads)
    tasks = [(chunk, difficulty, epsilon, seed, max_actions, branching)
             for chunk in _chunks(seeds, workers)]
    episodes = _drive(_run_chunk, tasks, len(seeds), workers, progress)
    # Seeds carry a split too: the bank's ranges are the project's convention
    # for which levels may be trained on, whoever generated them.
    shard = _collect(episodes, epsilon, seed, max_actions, branching,
                     split=_split_of([{"seed": value} for value in seeds]))
    shard["meta"]["difficulty"] = difficulty  # asked for, even if no level survived
    return shard


def _merge(shards):
    """One shard out of several, for the write-when-full path in `main`."""
    merged = {key: np.concatenate([shard[key] for shard in shards]) for key in ARRAYS}
    totals = ("episodes", "completed_episodes", "hopeless_rollouts", "steps",
              "deviation_branches", "hopeless_branches", "pad_branches", "pad_adjacent_branches",
              "multi_optimal_samples", "mask_fallbacks")
    counts = {}
    for shard in shards:
        for key, count in shard["meta"]["difficulty_counts"].items():
            counts[key] = counts.get(key, 0) + count
    merged["meta"] = {**shards[0]["meta"],
                      **{key: sum(shard["meta"][key] for shard in shards) for key in totals},
                      "seeds": [seed for shard in shards for seed in shard["meta"]["seeds"]],
                      "samples": int(len(merged["frames"])), "difficulty_counts": counts,
                      "optimal_set_mean": round(sum(shard["meta"]["optimal_set_mean"]
                                                    * shard["meta"]["samples"] for shard in shards)
                                                / max(1, len(merged["frames"])), 4),
                      "difficulty": _difficulty(counts),
                      "oracle_lengths": [n for shard in shards for n in shard["meta"]["oracle_lengths"]]}
    return merged


def _optimal_column(shard):
    """A shard from before the mask existed means "this one action was optimal"."""
    if "optimal" in shard:
        return shard["optimal"]
    return np.left_shift(1, shard["actions"].astype(np.int16)).astype(np.uint8)


def write_shard(path, shard):
    """Write through an open file: `savez_compressed` would otherwise append
    `.npz` to a name that lacks it and the returned path would be a lie."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = {key: shard[key] for key in ARRAYS if key != "optimal"}
    with open(path, "wb") as handle:
        np.savez_compressed(handle, meta=np.array(json.dumps(shard["meta"], sort_keys=True)),
                            optimal=_optimal_column(shard), **columns)
    return path


def read_shard(path):
    """A v1 shard reads back as v2 with a single-action mask, so old data trains."""
    with np.load(path, allow_pickle=False) as data:
        shard = {key: data[key] for key in ARRAYS if key in data.files}
        shard["meta"] = json.loads(str(data["meta"].item()))
    shard["optimal"] = _optimal_column(shard)
    return shard


def load_shards(paths):
    """Concatenate shards, keeping one meta dict each so seeds stay traceable."""
    shards = []
    for path in paths:
        shard = read_shard(path)
        if shard["meta"].get("format") not in (DATA_FORMAT,) + LEGACY_FORMATS:
            raise ValueError(f"{path} holds {shard['meta'].get('format')!r} data, not {DATA_FORMAT} "
                             f"or {LEGACY_FORMATS}")
        shards.append(shard)
    merged = {key: np.concatenate([shard[key] for shard in shards]) if shards else _blank()[key]
              for key in ARRAYS}
    merged["meta"] = [shard["meta"] for shard in shards]
    return merged


# -- CLI -----------------------------------------------------------------------

def _shard_path(out, index):
    """PATH.0000.npz, without doubling a `.npz` the caller already wrote."""
    stem = out.with_suffix("") if out.suffix == ".npz" else out
    return stem.with_name(f"{stem.name}.{index:04d}.npz")


def _groups(items, shard_size, max_actions):
    """Generate in level batches that cannot overflow one shard, so an episode is
    never split across files. The batch size must not depend on --workers, or
    shard boundaries would stop being reproducible."""
    size = max(1, shard_size // max(1, max_actions))
    return [items[index:index + size] for index in range(0, len(items), size)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bank", type=Path, help="A bank of verified specs; the split of record")
    parser.add_argument("--limit", type=int, help="Take only the first N levels of the bank")
    parser.add_argument("--levels", type=int, help="Levels to generate on demand (default 64)")
    parser.add_argument("--difficulty", type=int, help="Difficulty for on-demand levels (default 1)")
    parser.add_argument("--seed", type=int, help="First level seed, and the rollout RNG seed (default 0)")
    parser.add_argument("--epsilon", type=float,
                        help="Chance of a random action per step; 0 on a bank, .05 on seeds, and "
                             "above ~.1 it stops levels completing")
    parser.add_argument("--out", type=Path, default=Path("data/ls20-oracle.npz"))
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--max-actions", type=int, default=MAX_ACTIONS)
    parser.add_argument("--deviations", type=int, default=DEVIATIONS,
                        help="Prefix-replay branches per level; the main source of off-path states")
    parser.add_argument("--deviation-follow", type=int, default=DEVIATION_FOLLOW,
                        help="Oracle-guided recovery steps recorded after each deliberate mistake")
    parser.add_argument("--deviation-steps", type=int, default=DEVIATION_STEPS,
                        help="A branch strays 1..this many actions; one action barely leaves the path")
    parser.add_argument("--pad-branches", type=int, default=PAD_BRANCHES,
                        help="Branches per level that walk up to a goal pad carrying the wrong triple")
    parser.add_argument("--shard-size", type=int, help="Split into PATH.0000.npz... above this many samples")
    args = parser.parse_args()
    if args.bank and any(value is not None for value in (args.levels, args.difficulty, args.seed)):
        parser.error("--bank carries its own levels, difficulties and seeds; drop "
                     "--levels/--difficulty/--seed")
    if args.limit is not None and not args.bank:
        parser.error("--limit only applies to --bank")
    levels = 64 if args.levels is None else args.levels
    difficulty = 1 if args.difficulty is None else args.difficulty
    rng_seed = 0 if args.seed is None else args.seed
    # A bank is already verified and its levels are expensive to plan, so noise
    # is off by default there and the on-path pass stays free.
    epsilon = (0. if args.bank else EPSILON) if args.epsilon is None else args.epsilon
    if min(levels, difficulty, args.max_actions, args.workers, args.deviation_follow,
           args.deviation_steps) < 1:
        parser.error("levels, difficulty, max-actions, deviation-follow, deviation-steps and "
                     "workers must be positive")
    if args.limit is not None and args.limit < 1:
        parser.error("limit must be positive")
    if args.deviations < 0 or args.pad_branches < 0:
        parser.error("deviations and pad-branches must not be negative")
    if not 0 <= epsilon <= 1:
        parser.error("epsilon must be between 0 and 1")
    if not 0 <= rng_seed <= 2**32 - 1 - levels:
        parser.error("level seeds must fit in uint32")
    if args.shard_size is not None and args.shard_size < 1:
        parser.error("shard-size must be positive")

    if args.bank:
        items = load_bank(args.bank, args.limit)
        if not items:
            parser.error(f"{args.bank} holds no levels")
    else:
        items = list(range(rng_seed, rng_seed + levels))
    groups = _groups(items, args.shard_size, args.max_actions) if args.shard_size else [items]
    written, metas, pending = [], [], []
    for group in groups:
        if args.bank:
            shard = generate_shard_from_specs(group, epsilon, rng_seed, args.max_actions, args.workers,
                                              True, args.deviations, args.deviation_follow,
                                              args.deviation_steps, args.pad_branches, args.bank)
        else:
            shard = generate_shard(group, difficulty, epsilon, rng_seed, args.max_actions,
                                   args.workers, True, args.deviations, args.deviation_follow,
                                   args.deviation_steps, args.pad_branches)
        filled = sum(item["meta"]["samples"] for item in pending) + shard["meta"]["samples"]
        if pending and args.shard_size and filled > args.shard_size:
            full = _merge(pending)
            written.append(write_shard(_shard_path(args.out, len(written)), full))
            metas.append(full["meta"])
            pending = []
        pending.append(shard)
    merged = _merge(pending)
    # A numbered name is only right once a second file exists, which is exactly
    # when the first flush above already happened.
    written.append(write_shard(_shard_path(args.out, len(written)) if written else args.out, merged))
    metas.append(merged["meta"])
    samples = sum(meta["samples"] for meta in metas)
    episodes = sum(meta["episodes"] for meta in metas)
    completed = sum(meta["completed_episodes"] for meta in metas)
    branches = sum(meta["deviation_branches"] for meta in metas)
    hopeless = sum(meta["hopeless_branches"] for meta in metas)
    pads = sum(meta["pad_branches"] for meta in metas)
    adjacent = sum(meta["pad_adjacent_branches"] for meta in metas)
    counts = {}
    for meta in metas:
        for key, count in meta["difficulty_counts"].items():
            counts[key] = counts.get(key, 0) + count
    print(f"{samples} samples | {episodes} episodes | {completed} completed "
          f"({completed / max(1, episodes):.0%}) | {branches} deviation branches, {hopeless} hopeless | "
          f"{pads} pad branches, {adjacent} reached a mismatched pad | "
          f"epsilon {epsilon} | split {metas[0]['split']} | "
          f"difficulties {dict(sorted(counts.items()))} | "
          f"generator {metas[0]['generator_version']}", flush=True)
    for path in written:
        print(f"Saved {path}", flush=True)


if __name__ == "__main__":
    main()
